@model=/template
@id=2
@status=true
### @name get_all
GET {{host_address}}{{prefix}}{{model}}
Accept: application/json
### @name get_by_id
GET {{host_address}}{{prefix}}{{model}}/{{id}}
Accept: application/json
### @name get_by_status
GET {{host_address}}{{prefix}}{{model}}/active/{{status}}
Accept: application/json
### @name create
POST {{host_address}}{{prefix}}{{model}}
Content-Type: application/json
{
  "nombre":"PRUEBA CREAR DESDE JSON",
  "activo":true,
  "plantillaPasos":[
    {
      "orden":1,
      "usuarioAprobadorId":15
    },
    {
      "orden":2,
      "usuarioAprobadorId":15
    },
    {
      "orden":3,
      "usuarioAprobadorId":15
    },
    {
      "orden":4,
      "usuarioAprobadorId":15
    },
    {
      "orden":5,
      "usuarioAprobadorId":15
    }
  ]
}
### @name update
PUT {{host_address}}{{prefix}}{{model}}/{{id}}
Content-Type: application/json
{
  "id":{{id}},
  "nombre":"put"
}
### @name patch
PATCH {{host_address}}{{prefix}}{{model}}/{{id}}
Content-Type: application/json
{
  "activo":true
}
### @name delete
DELETE {{host_address}}{{prefix}}{{model}}/{{id}}
### @name open_api
GET {{host_address}}/openapi/v1.json
Accept: application/json